PLUGIN_NAME=    patrium-speedtest
PLUGIN_VERSION= 1.0
PLUGIN_COMMENT= Speedtest CLI Plugin for OPNsense 25.x
PLUGIN_DEPENDS=
PLUGIN_MAINTAINER=oss-feedback@patrium.net

.include "../../Mk/plugins.mk"
